#!/bin/bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Create, sign, and upload contract to Azure Blob Storage
#
# This script:
# 1. Loads DID credentials generated by 1-generate-dids.sh
# 2. Creates contract JSON with actual DIDs and Azure resource references
# 3. Signs contract with TDP, TDC, and CCRP keys (multi-signature)
# 4. Uploads signed contract (COSE format) to Azure Blob Storage
# 5. Uploads trust store for signature verification

set -e

# Configuration
: ${DID_DIR:="./did-credentials"}
: ${CONTRACT_TEMPLATE:="../../contract/contract.json"}
: ${OUTPUT_DIR:="./contract-output"}
: ${AZURE_STORAGE_ACCOUNT_NAME:?"AZURE_STORAGE_ACCOUNT_NAME not set"}
: ${AZURE_STORAGE_ACCOUNT_KEY:?"AZURE_STORAGE_ACCOUNT_KEY not set"}
: ${AZURE_CONTAINER_NAME:="pilot-contracts"}
: ${CONTRACT_VERSION:="2.15"}
: ${FEED_NAME:="covid-training-pilot"}

echo "=================================================="
echo "Creating and Signing Contract"
echo "=================================================="
echo ""

# Check that DIDs have been generated
if [ ! -d "$DID_DIR" ]; then
    echo "ERROR: DID directory not found: $DID_DIR"
    echo "Please run 1-generate-dids.sh first"
    exit 1
fi

# Load DIDs from environment
source "$DID_DIR/did_env.sh"

echo "Configuration:"
echo "  TDP DID: $TDP_DID"
echo "  TDC DID: $TDC_DID"
echo "  CCRP DID: $CCRP_DID"
echo "  Contract Template: $CONTRACT_TEMPLATE"
echo "  Storage Account: $AZURE_STORAGE_ACCOUNT_NAME"
echo "  Container: $AZURE_CONTAINER_NAME"
echo "  Contract Version: $CONTRACT_VERSION"
echo ""

# Create output directory
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Step 1: Create contract JSON with actual DIDs and resource references
echo "----------------------------------------"
echo "Step 1: Creating Contract JSON"
echo "----------------------------------------"

# Read template and substitute environment variables and DIDs
CONTRACT_JSON=$(cat "$CONTRACT_TEMPLATE" | \
    jq --arg tdc "$TDC_DID" '.tdc = $tdc' | \
    jq --arg tdp "$TDP_DID" '.tdps = [$tdp]' | \
    jq --arg ccrp "$CCRP_DID" '.ccrp = $ccrp' | \
    jq --arg storage "$AZURE_STORAGE_ACCOUNT_NAME" '
        .datasets |= map(
            .url |= gsub("\\$AZURE_STORAGE_ACCOUNT_NAME"; $storage) |
            .provider = $ARGS.named.tdp
        )
    ' --arg tdp "$TDP_DID" | \
    envsubst)

# Update dataset provider DIDs
CONTRACT_JSON=$(echo "$CONTRACT_JSON" | \
    jq --arg tdp "$TDP_DID" '.datasets[].provider = $tdp')

# Save contract JSON
echo "$CONTRACT_JSON" | jq '.' > "$OUTPUT_DIR/contract.json"
echo "✓ Contract JSON created: $OUTPUT_DIR/contract.json"
echo ""

# Step 2: Sign contract with TDP key (first signature)
echo "----------------------------------------"
echo "Step 2: Signing Contract with TDP Key"
echo "----------------------------------------"

scitt sign-contract \
    --contract "$OUTPUT_DIR/contract.json" \
    --content-type "application/json" \
    --did-doc "$DID_DIR/TDP/did.json" \
    --key "$DID_DIR/TDP/key.pem" \
    --feed "$FEED_NAME" \
    --out "$OUTPUT_DIR/contract-tdp-signed.cose"

echo "✓ Contract signed by TDP"
echo ""

# Step 3: Add TDC signature
echo "----------------------------------------"
echo "Step 3: Adding TDC Signature"
echo "----------------------------------------"

scitt sign-contract \
    --contract "$OUTPUT_DIR/contract-tdp-signed.cose" \
    --content-type "application/cose" \
    --did-doc "$DID_DIR/TDC/did.json" \
    --key "$DID_DIR/TDC/key.pem" \
    --add-signature \
    --out "$OUTPUT_DIR/contract-tdp-tdc-signed.cose"

echo "✓ Contract signed by TDC"
echo ""

# Step 4: Add CCRP signature (optional but recommended)
echo "----------------------------------------"
echo "Step 4: Adding CCRP Signature"
echo "----------------------------------------"

scitt sign-contract \
    --contract "$OUTPUT_DIR/contract-tdp-tdc-signed.cose" \
    --content-type "application/cose" \
    --did-doc "$DID_DIR/CCRP/did.json" \
    --key "$DID_DIR/CCRP/key.pem" \
    --add-signature \
    --out "$OUTPUT_DIR/contract-signed.cose"

echo "✓ Contract signed by CCRP"
echo ""

# Step 5: Upload signed contract to Azure Blob Storage
echo "----------------------------------------"
echo "Step 5: Uploading to Azure Blob Storage"
echo "----------------------------------------"

# Install Azure CLI tools if needed
if ! python3 -c "import azure.storage.blob" 2>/dev/null; then
    echo "Installing azure-storage-blob..."
    pip3 install --quiet azure-storage-blob
fi

# Upload using Python (more reliable than az cli)
python3 << EOF
from azure.storage.blob import BlobServiceClient
import sys

try:
    # Connect to storage account
    connection_string = f"DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_ACCOUNT_NAME};AccountKey=${AZURE_STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net"
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)

    # Get container client (create if doesn't exist)
    container_client = blob_service_client.get_container_client("${AZURE_CONTAINER_NAME}")
    try:
        container_client.create_container()
        print(f"✓ Created container: ${AZURE_CONTAINER_NAME}")
    except Exception as e:
        if "ContainerAlreadyExists" not in str(e):
            raise
        print(f"✓ Using existing container: ${AZURE_CONTAINER_NAME}")

    # Upload signed contract (COSE format)
    with open("${OUTPUT_DIR}/contract-signed.cose", "rb") as data:
        blob_client = container_client.get_blob_client("${CONTRACT_VERSION}.cose")
        blob_client.upload_blob(data, overwrite=True)
        print(f"✓ Uploaded signed contract: ${CONTRACT_VERSION}.cose")

    # Also upload JSON for debugging/reference
    with open("${OUTPUT_DIR}/contract.json", "rb") as data:
        blob_client = container_client.get_blob_client("${CONTRACT_VERSION}.json")
        blob_client.upload_blob(data, overwrite=True)
        print(f"✓ Uploaded contract JSON: ${CONTRACT_VERSION}.json")

    print(f"\\nBlob URLs:")
    print(f"  COSE: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_CONTAINER_NAME}/${CONTRACT_VERSION}.cose")
    print(f"  JSON: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_CONTAINER_NAME}/${CONTRACT_VERSION}.json")

except Exception as e:
    print(f"ERROR uploading to blob storage: {e}", file=sys.stderr)
    sys.exit(1)
EOF

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to upload contract to blob storage"
    exit 1
fi

echo ""

# Step 6: Create and upload trust store
echo "----------------------------------------"
echo "Step 6: Uploading Trust Store"
echo "----------------------------------------"

# Create trust store directory structure for upload
TRUST_STORE_UPLOAD="$OUTPUT_DIR/trust_store"
mkdir -p "$TRUST_STORE_UPLOAD"

# Copy DID documents
cp "$DID_DIR/TDP/did.json" "$TRUST_STORE_UPLOAD/tdp.json"
cp "$DID_DIR/TDC/did.json" "$TRUST_STORE_UPLOAD/tdc.json"
cp "$DID_DIR/CCRP/did.json" "$TRUST_STORE_UPLOAD/ccrp.json"

# Create trust store index
jq -n \
    --arg tdp "$TDP_DID" \
    --arg tdc "$TDC_DID" \
    --arg ccrp "$CCRP_DID" \
    '{
        "version": "1.0",
        "participants": [
            {"role": "TDP", "did": $tdp, "did_doc": "tdp.json"},
            {"role": "TDC", "did": $tdc, "did_doc": "tdc.json"},
            {"role": "CCRP", "did": $ccrp, "did_doc": "ccrp.json"}
        ],
        "created": now | strftime("%Y-%m-%dT%H:%M:%SZ")
    }' > "$TRUST_STORE_UPLOAD/trust_store.json"

# Upload trust store files
python3 << EOF
from azure.storage.blob import BlobServiceClient
import sys
import os

try:
    connection_string = f"DefaultEndpointsProtocol=https;AccountName=${AZURE_STORAGE_ACCOUNT_NAME};AccountKey=${AZURE_STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net"
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    container_client = blob_service_client.get_container_client("${AZURE_CONTAINER_NAME}")

    # Upload trust store files
    trust_store_files = ["trust_store.json", "tdp.json", "tdc.json", "ccrp.json"]
    for filename in trust_store_files:
        with open(f"${TRUST_STORE_UPLOAD}/{filename}", "rb") as data:
            blob_client = container_client.get_blob_client(f"trust_store/{filename}")
            blob_client.upload_blob(data, overwrite=True)
            print(f"✓ Uploaded: trust_store/{filename}")

except Exception as e:
    print(f"ERROR uploading trust store: {e}", file=sys.stderr)
    sys.exit(1)
EOF

if [ $? -ne 0 ]; then
    echo "ERROR: Failed to upload trust store"
    exit 1
fi

echo ""

echo "=================================================="
echo "Contract Creation and Signing Complete!"
echo "=================================================="
echo ""
echo "Outputs:"
echo "  Local contract JSON: $OUTPUT_DIR/contract.json"
echo "  Local signed COSE:   $OUTPUT_DIR/contract-signed.cose"
echo "  Local trust store:   $TRUST_STORE_UPLOAD/"
echo ""
echo "Azure Blob Storage:"
echo "  Signed contract: https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_CONTAINER_NAME}/${CONTRACT_VERSION}.cose"
echo "  Contract JSON:   https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_CONTAINER_NAME}/${CONTRACT_VERSION}.json"
echo "  Trust store:     https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${AZURE_CONTAINER_NAME}/trust_store/trust_store.json"
echo ""
echo "Next steps:"
echo "  1. Verify uploads in Azure Portal"
echo "  2. Test contract retrieval and signature verification"
echo "  3. Run deployment with: CONTRACT_STORAGE_MODE=blob ./deploy.sh"
echo ""
